services:
  - type: web
    name: passive-income-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGODB_URI
        scope: build,runtime
        sync: false
      - key: JWT_SECRET
        scope: build,runtime
        sync: false
      - key: NODE_ENV
        value: production
